trigger:
  - Teste_da_pipeline


pool:
  vmImage: ubuntu-latest

stages:

  - stage: Build
    displayName: "Build e Push para ACR"
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'pythonmssqlrm560416'
              repository: 'pythonmssql'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest
          - task: Docker@2
            displayName: "Push para ACR"
            inputs:
              containerRegistry: "pythonmssqlrm560416"
              repository:        "pythonmssql"
              command:           "push"
              tags: |
                $(Build.BuildId)
                latest

  - stage: Deploy
    displayName: "Deploy no ACI"
    dependsOn: Build
    jobs:
      - job: DeployACI
        steps:
          - task: AzureCLI@2
            displayName: "Criar container no ACI"
            inputs:
              azureSubscription: "Azure for Students (b2791124-b4e1-4efc-9b65-037eb38699a4)"
              scriptType:        "bash"
              scriptLocation:    "inlineScript"
              inlineScript: |
                az container delete \
                  --resource-group rg-azuredevops-docker \
                  --name pythonmssqlrm560416 \
                  --yes

                az container create \
                  --resource-group rg-azuredevops-docker \
                  --name pythonmssqlrm560416 \
                  --image pythonmssqlrm560416.azurecr.io/pythonmssql:latest \
                  --cpu 2 \
                  --memory 2 \
                  --os-type Linux \
                  --registry-login-server pythonmssqlrm560416.azurecr.io \
                  --registry-username pythonmssqlrm560416 \
                  --registry-password CnKEWGYqrSdT5rYhc7WiS0TBwRyUOk4zFpSwObTylpdOCCsiDe0dJQQJ99CEACR0EKYEqg7NAAACAZCRLWbE \
                  --dns-name-label pythonmssqlrm560416 \
                  --restart-policy Always \
                  --ports 80 \
                  --environment-variables \
                    DB_USER="user-dimdimsql" \
                    DB_PASSWORD="PRd23112025@" \
                    DB_HOST="sql-server-dimdim-rm560416-spaincentral.database.windows.net" \
                    DB_NAME="db-dimdim"
                    DB_PORT="1433"