trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ConnectedServiceName: '178990e3-3232-4099-b0b8-c39f62835b42'
  WebAppKind: 'webAppLinux'
  WebAppName: 'jokenpo'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install flask
  displayName: "Install dependencies"

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

# DEPLOY (APP SERVICE)
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(ConnectedServiceName)'
    appType: 'webAppLinux'
    WebAppName: '$(WebAppName)'
    packageForLinux: '$(System.ArtifactsDirectory)/drop/app.zip'