trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  WebAppName: 'jokenpo'

steps:

# 1. Configura o Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Use Python 3.11'

# 2. Instala dependências
- script: |
    python -m pip install --upgrade pip
    pip install flask
  displayName: 'Install dependencies'

# 3. Teste básico
- script: |
    python -c "import jokenpo"
  displayName: 'Test import'

# === NOVA TAREFA: CONSTRÓI E ENVIA PARA O AZURE CONTAINER REGISTRY (ACR) ===
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: dotnetmssqlrm560416 # O assistente preenche isto automaticamente
    repository: 'jokenpo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

# 4. ZIP da aplicação (Mantido para cumprir a segunda exigência)
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Create ZIP package'

# 5. Publica o artefacto ZIP
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop
  displayName: 'Publish Artifact'